### ISSUE TITLE
Mock convenient BIS functions and commands

### ISSUE THREAD

**Issue by xetra11** [X39/sqf-vm#22]
I played around with your tool and well found it pretty cool for hacking some sqf scripts while on the run. But I am missing the use of commands and functions like `findNearestEnemy`.

I was tinkering in my head if it might be a solution if we have to provide some kind of mocked function list. For instance consider this `mock-function.sqfmock` fictional file (I am scripting for a month - please don't judge my syntax):

```
var mockedUnits  = createGroup west; // create a mockedUnits group
var mockedFoundEnemy = mockedUnits createUnit [type, position, markers, placement, special] // setting right parameters
_ findNearestEnemy _ >> mockedFoundEnemy // tell the function with >> to return the given object regardless of the parameters given (type, etc.)
```
**Explaination**
The first two lines are the test objects that have to be created because `findNearestEnemy` should return the `mockedFoundEnemy` regardless with what parameters the function is called ( the `_ `indicates a wildcard for parameters)

So after "loading" this `mock-function.sqfmock` into the CLI I can run the following within the REPL

```
// objects defined before this
someObject findNearestEnemy somePosition;
```

And the REPL will return the `mockedFoundEnemy` object. This way I am able to write my functions and use these commands and BIS functions. Implied that this  `mock-function.sqfmock` has the needed functions mocked which is a good piece of work - but hey - maybe a community could kind of contribute to a huge mock file.

I hope you understand what I mean

PS: The idea and syntax is inspired by the Java Spock Testing Framework

**Comment by X39** [comment]
well ... theoretically, that is not really needed.
according to biki, `object findNearestEnemy position` is the expectation for `findNearestEnemy`

problem now is: one just has to implement the command

afterwards, the mock situation, would just be normal SQF code (you would have to spawn those units yourself and set the position according) :)

for methods, it is kinda correct that there is currently no full export of all BIS functions sadly and thus you cannot "just include" the full BIS functions into the sqf-vm (thus you have to export them first, and take them with you then at which point you can feed it to the CLI either via param `-f <PATH>,  --sqf-file <PATH>  (accepted multiple times)` or just simple pasting when already in CLI)

Feel free to suggest commands that should be implemented next 👍 will take care that those are handled with priority


if i missunderstood the request, please clarify

**Comment by X39** [comment]
Feel free to reopen if you feel that this is not yet done :)
